[ui]
default-command = ["log", "-r", "@ | ancestors(remote_bookmarks().., 2) | trunk()"]
diff-instructions = false

[templates]
git_push_bookmark = '"sgilson/push-" ++ change_id.short()'

[revset-aliases]
stack = "trunk()-..@"

