#!/usr/bin/env zsh

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

# Start notes in quick terminal
if [[ "$GHOSTTY_QUICK_TERMINAL" == 1 ]]; then
  exec nvim -c 'norm G$' -c 'autocmd User VeryLazy lua require("lualine").hide()' ~/Documents/notes.md
fi

# Start zinit
## Setup
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
[ ! -d $ZINIT_HOME ] && mkdir -p "$(dirname $ZINIT_HOME)"
[ ! -d $ZINIT_HOME/.git ] && git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
source "${ZINIT_HOME}/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

## Plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

## Load completions
## https://gist.github.com/ctechols/ca1035271ad134841284#file-compinit-zsh-L2
autoload -Uz compinit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
	compinit;
else
	compinit -C;
fi;

zinit cdreplay -q

# End zinit

# Improve history settings

HISTSIZE=9999999
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

if (( $+commands[mise] )); then
  eval "$(mise activate zsh)"
fi

source ~/.zsh-prompt

if (( $+commands[kubectl] )); then
  source <(kubectl completion zsh)
  compdef __start_kubectl k
fi

if (( $+commands[sqlx] )); then
  source <(sqlx completions zsh)
fi

if (( $+commands[fzf] )); then
  eval "$(fzf --zsh)"
fi

if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh --cmd cd)"
fi

if (( $+commands[delta] )); then
  eval "$(delta --generate-completion zsh)"
fi

if (( $+commands[jj] )); then
  source <(jj util completion zsh)
fi


typeset -gA EXPECTED_DEPS=(
  git     "version control (used by prompt + aliases)"
  mise    "runtime version manager"
  fzf     "fuzzy finder"
  zoxide  "smart cd"
  delta   "git diff pager"
  kubectl "kubernetes CLI"
  sqlx    "sqlx-cli completions"
  lsd     "ls replacement"
  bat     "syntax-highlighted cat"
  nvim    "editor"
  gdate   "GNU date (macOS)"
)

check-deps() {
  local name max=0 missing=0
  for name in ${(k)EXPECTED_DEPS}; do
    (( ${#name} > max )) && max=${#name}
  done
  for name in ${(ok)EXPECTED_DEPS}; do
    if (( $+commands[$name] )); then
      printf "  %-${max}s  %s%-7s%s  %s\n" "$name" $'\e[32m' ok $'\e[0m' "${EXPECTED_DEPS[$name]}"
    else
      printf "  %-${max}s  %s%-7s%s  %s\n" "$name" $'\e[31m' missing $'\e[0m' "${EXPECTED_DEPS[$name]}"
      (( missing++ ))
    fi
  done
  return $(( missing > 0 ))
}

source ~/.aliases

export EDITOR=nvim

for cmd in nvim vim vi; do
  if (( $+commands[$cmd] )); then
    export EDITOR=$cmd
    break
  fi
done
export VISUAL=$EDITOR

KEYTIMEOUT=1

bindkey -v
bindkey "^H" backward-delete-char
bindkey "^?" backward-delete-char
bindkey ' ' magic-space

# requires vim keybindings
bindkey -s '^Xgc' 'git commit -s -m ""\eha'
bindkey -s '^Xgs' 'git switch ""\eha'

